# Template for local ESPHome credentials.
# Do not commit real values to source control.

mqtt_host: 192.168.1.10
mqtt_username: your_mqtt_user
mqtt_password: your_mqtt_password

wifi_ssid: your_wifi_ssid
wifi_password: your_wifi_password

encryption_key: your_home_assistant_api_encryption_key

# Fallback WiFi Access Point password
ap_password: your_fallback_ap_password
# Password used to remotely flash firmware
ota_password: your_ota_password
