# you must change to you purpose

mqtt_host: iobroker.fritz.box
mqtt_port: 1886
mqtt_username: iobrokerMQTT
mqtt_password: CMea4C2hp5Eg
  
wifi_ssid: Midgard
wifi_password: 7duqke8EHVgmxMQ27

encryption_key: noname
  
# Fallback WiFi Access Point password
ap_password: _#_Fallback
# Password used to remotely flash firmware
ota_password: _#_Fallback

