# you must change to you purpose

mqtt_host: 192.168.1.1
mqtt_username: mqttun
mqtt_password: mqttpw
  
wifi_ssid: www.mywifi.com
wifi_password: TopSecret

encryption_key: noname
  
# Fallback WiFi Access Point password
ap_password: ts@AP
# Password used to remotely flash firmware
ota_password: ts@OtA


 